---

- name: Make sure apt-transport-https is installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
 
- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://ha.pool.sks-keyservers.net:80 "
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    update_cache: yes
    state: present

- raw: sudo apt-get update

- name: apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual 
  shell: >
    apt-get -y  install linux-image-extra-$(uname -r) linux-image-extra-virtual 

- name: apt-get install docker-engine
  shell: >
    apt-get -y install docker-engine

- name: Make sure docker is running
  service:
    name: docker
    state: started

